parameters:
#    auditoria.example.class: STG\DEIM\Auditoria\Bundle\AuditoriaBundle\Example

services:
    stg.deim.auditoria.auditoria.auditoria:
        class: STG\DEIM\Auditoria\Bundle\AuditoriaBundle\Services\AuditoriaService
        arguments: ['@logger', '@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: onFlush }
